[project]
name = "styleflow-content-fixed-i2i"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy==1.17.3",
    "tensorboard==2.0.0",
    "torch==1.5.0",
    "torchvision==0.6.0",
]
